namespace Sol.Api.Services;

public static class AuthoritativeCatalogManifest
{
  public static IReadOnlyList<AuthoritativeCatalogTarget> Targets { get; } =
  [
    new("sun", "Sun", "Star", "star", null, 0, HorizonsCommand: "10"),
    new("mercury", "Mercury", "Planet", "planet", "sun", 100, HorizonsCommand: "199"),
    new("venus", "Venus", "Planet", "planet", "sun", 110, HorizonsCommand: "299"),
    new("earth", "Earth", "Planet", "planet", "sun", 120, HorizonsCommand: "399"),
    new("mars", "Mars", "Planet", "planet", "sun", 130, HorizonsCommand: "499"),
    new("jupiter", "Jupiter", "Planet", "planet", "sun", 140, HorizonsCommand: "599"),
    new("saturn", "Saturn", "Planet", "planet", "sun", 150, HorizonsCommand: "699"),
    new("uranus", "Uranus", "Planet", "planet", "sun", 160, HorizonsCommand: "799"),
    new("neptune", "Neptune", "Planet", "planet", "sun", 170, HorizonsCommand: "899"),
    new("ceres", "Ceres", "Dwarf Planet", "dwarf-planet", "sun", 2000, SbdbDesignation: "1", HorizonsCommand: "1;"),
    new("pluto", "Pluto", "Dwarf Planet", "dwarf-planet", "sun", 2010, SbdbDesignation: "134340", HorizonsCommand: "134340;"),
    new("eris", "Eris", "Dwarf Planet", "dwarf-planet", "sun", 2020, SbdbDesignation: "136199", HorizonsCommand: "136199;"),
    new("makemake", "Makemake", "Dwarf Planet", "dwarf-planet", "sun", 2030, SbdbDesignation: "136472", HorizonsCommand: "136472;"),
    new("haumea", "Haumea", "Dwarf Planet", "dwarf-planet", "sun", 2040, SbdbDesignation: "136108", HorizonsCommand: "136108;"),
    new("sedna", "Sedna", "Dwarf Planet", "dwarf-planet", "sun", 2050, SbdbDesignation: "90377", HorizonsCommand: "90377;"),
    new("gonggong", "Gonggong", "Dwarf Planet", "dwarf-planet", "sun", 2060, SbdbDesignation: "225088", HorizonsCommand: "225088;"),
    new("quaoar", "Quaoar", "Dwarf Planet", "dwarf-planet", "sun", 2070, SbdbDesignation: "50000", HorizonsCommand: "50000;"),
    new("orcus", "Orcus", "Dwarf Planet", "dwarf-planet", "sun", 2080, SbdbDesignation: "90482", HorizonsCommand: "90482;"),
    new("halley", "Halley", "Comet", "comet", "sun", 3000, SbdbDesignation: "1P", HorizonsCommand: "DES=1P;CAP;NOFRAG"),
    new("hale-bopp", "Hale-Bopp", "Comet", "comet", "sun", 3010, SbdbDesignation: "C/1995 O1", HorizonsCommand: "DES=C/1995 O1;CAP;NOFRAG"),
    new("hyakutake", "Hyakutake", "Comet", "comet", "sun", 3020, SbdbDesignation: "C/1996 B2", HorizonsCommand: "DES=C/1996 B2;CAP;NOFRAG"),
    new("encke", "Encke", "Comet", "comet", "sun", 3030, SbdbDesignation: "2P", HorizonsCommand: "DES=2P;CAP;NOFRAG"),
    new("67p-churyumov-gerasimenko", "67P/Churyumov-Gerasimenko", "Comet", "comet", "sun", 3040, SbdbDesignation: "67P", HorizonsCommand: "DES=67P;CAP;NOFRAG"),
    new("tempel-1", "Tempel 1", "Comet", "comet", "sun", 3050, SbdbDesignation: "9P", HorizonsCommand: "DES=9P;CAP;NOFRAG"),
    new("wild-2", "Wild 2", "Comet", "comet", "sun", 3060, SbdbDesignation: "81P", HorizonsCommand: "DES=81P;CAP;NOFRAG"),
    new("shoemaker-levy-9", "Shoemaker-Levy 9", "Comet", "comet", "sun", 3070, SbdbDesignation: "1993 F2-A", HorizonsCommand: "DES=1993 F2-A;CAP"),
    Fragment("shoemaker-levy-9-fragment-a", "Shoemaker-Levy 9 Fragment A", "shoemaker-levy-9", 3071, "1993 F2-A"),
    Fragment("shoemaker-levy-9-fragment-b", "Shoemaker-Levy 9 Fragment B", "shoemaker-levy-9", 3072, "1993 F2-B"),
    Fragment("shoemaker-levy-9-fragment-c", "Shoemaker-Levy 9 Fragment C", "shoemaker-levy-9", 3073, "1993 F2-C"),
    Fragment("shoemaker-levy-9-fragment-d", "Shoemaker-Levy 9 Fragment D", "shoemaker-levy-9", 3074, "1993 F2-D"),
    Fragment("shoemaker-levy-9-fragment-e", "Shoemaker-Levy 9 Fragment E", "shoemaker-levy-9", 3075, "1993 F2-E"),
    Fragment("shoemaker-levy-9-fragment-f", "Shoemaker-Levy 9 Fragment F", "shoemaker-levy-9", 3076, "1993 F2-F"),
    Fragment("shoemaker-levy-9-fragment-g", "Shoemaker-Levy 9 Fragment G", "shoemaker-levy-9", 3077, "1993 F2-G"),
    Fragment("shoemaker-levy-9-fragment-h", "Shoemaker-Levy 9 Fragment H", "shoemaker-levy-9", 3078, "1993 F2-H"),
    Fragment("shoemaker-levy-9-fragment-k", "Shoemaker-Levy 9 Fragment K", "shoemaker-levy-9", 3079, "1993 F2-K"),
    Fragment("shoemaker-levy-9-fragment-l", "Shoemaker-Levy 9 Fragment L", "shoemaker-levy-9", 3080, "1993 F2-L"),
    Fragment("shoemaker-levy-9-fragment-n", "Shoemaker-Levy 9 Fragment N", "shoemaker-levy-9", 3081, "1993 F2-N"),
    Fragment("shoemaker-levy-9-fragment-p1", "Shoemaker-Levy 9 Fragment P1", "shoemaker-levy-9", 3082, "1993 F2-P1"),
    Fragment("shoemaker-levy-9-fragment-p2", "Shoemaker-Levy 9 Fragment P2", "shoemaker-levy-9", 3083, "1993 F2-P2"),
    Fragment("shoemaker-levy-9-fragment-q1", "Shoemaker-Levy 9 Fragment Q1", "shoemaker-levy-9", 3084, "1993 F2-Q1"),
    Fragment("shoemaker-levy-9-fragment-q2", "Shoemaker-Levy 9 Fragment Q2", "shoemaker-levy-9", 3085, "1993 F2-Q2"),
    Fragment("shoemaker-levy-9-fragment-r", "Shoemaker-Levy 9 Fragment R", "shoemaker-levy-9", 3086, "1993 F2-R"),
    Fragment("shoemaker-levy-9-fragment-s", "Shoemaker-Levy 9 Fragment S", "shoemaker-levy-9", 3087, "1993 F2-S"),
    Fragment("shoemaker-levy-9-fragment-t", "Shoemaker-Levy 9 Fragment T", "shoemaker-levy-9", 3088, "1993 F2-T"),
    Fragment("shoemaker-levy-9-fragment-u", "Shoemaker-Levy 9 Fragment U", "shoemaker-levy-9", 3089, "1993 F2-U"),
    Fragment("shoemaker-levy-9-fragment-v", "Shoemaker-Levy 9 Fragment V", "shoemaker-levy-9", 3090, "1993 F2-V"),
    Fragment("shoemaker-levy-9-fragment-w", "Shoemaker-Levy 9 Fragment W", "shoemaker-levy-9", 3091, "1993 F2-W"),
    new("neowise", "NEOWISE", "Comet", "comet", "sun", 3080, SbdbDesignation: "C/2020 F3", HorizonsCommand: "DES=C/2020 F3;CAP;NOFRAG"),
    new("ikeya-seki", "Ikeya-Seki", "Comet", "comet", "sun", 3090, SbdbDesignation: "1965 S1-A", HorizonsCommand: "DES=1965 S1-A;CAP"),
    new("voyager-1", "Voyager 1", "Space Probe", "probe", null, 4000, HorizonsCommand: "-31"),
    new("voyager-2", "Voyager 2", "Space Probe", "probe", null, 4010, HorizonsCommand: "-32"),

    Moon("moon", "Moon", "earth", 5000, "301"),
    Moon("phobos", "Phobos", "mars", 5010, "401"),
    Moon("deimos", "Deimos", "mars", 5020, "402"),

    Moon("io", "Io", "jupiter", 5100, "501"),
    Moon("europa", "Europa", "jupiter", 5110, "502"),
    Moon("ganymede", "Ganymede", "jupiter", 5120, "503"),
    Moon("callisto", "Callisto", "jupiter", 5130, "504"),
    Moon("amalthea", "Amalthea", "jupiter", 5140, "505"),
    Moon("himalia", "Himalia", "jupiter", 5150, "506"),
    Moon("elara", "Elara", "jupiter", 5160, "507"),
    Moon("pasiphae", "Pasiphae", "jupiter", 5170, "508"),
    Moon("sinope", "Sinope", "jupiter", 5180, "509"),
    Moon("lysithea", "Lysithea", "jupiter", 5190, "510"),
    Moon("carme", "Carme", "jupiter", 5200, "511"),
    Moon("ananke", "Ananke", "jupiter", 5210, "512"),
    Moon("leda", "Leda", "jupiter", 5220, "513"),
    Moon("thebe", "Thebe", "jupiter", 5230, "514"),
    Moon("adrastea", "Adrastea", "jupiter", 5240, "515"),
    Moon("metis", "Metis", "jupiter", 5250, "516"),

    Moon("mimas", "Mimas", "saturn", 5300, "601"),
    Moon("enceladus", "Enceladus", "saturn", 5310, "602"),
    Moon("tethys", "Tethys", "saturn", 5320, "603"),
    Moon("dione", "Dione", "saturn", 5330, "604"),
    Moon("rhea", "Rhea", "saturn", 5340, "605"),
    Moon("titan", "Titan", "saturn", 5350, "606"),
    Moon("hyperion", "Hyperion", "saturn", 5360, "607"),
    Moon("iapetus", "Iapetus", "saturn", 5370, "608"),
    Moon("phoebe", "Phoebe", "saturn", 5380, "609"),
    Moon("janus", "Janus", "saturn", 5390, "610"),
    Moon("epimetheus", "Epimetheus", "saturn", 5400, "611"),
    Moon("helene", "Helene", "saturn", 5410, "612"),
    Moon("telesto", "Telesto", "saturn", 5420, "613"),
    Moon("calypso", "Calypso", "saturn", 5430, "614"),
    Moon("atlas", "Atlas", "saturn", 5440, "615"),
    Moon("prometheus", "Prometheus", "saturn", 5450, "616"),
    Moon("pandora", "Pandora", "saturn", 5460, "617"),
    Moon("pan", "Pan", "saturn", 5470, "618"),
    Moon("daphnis", "Daphnis", "saturn", 5480, "635"),

    Moon("miranda", "Miranda", "uranus", 5500, "705"),
    Moon("ariel", "Ariel", "uranus", 5510, "701"),
    Moon("umbriel", "Umbriel", "uranus", 5520, "702"),
    Moon("titania", "Titania", "uranus", 5530, "703"),
    Moon("oberon", "Oberon", "uranus", 5540, "704"),
    Moon("caliban", "Caliban", "uranus", 5550, "716"),
    Moon("sycorax", "Sycorax", "uranus", 5560, "717"),
    Moon("prospero", "Prospero", "uranus", 5570, "718"),
    Moon("setebos", "Setebos", "uranus", 5580, "719"),
    Moon("puck", "Puck", "uranus", 5590, "715"),
    Moon("portia", "Portia", "uranus", 5600, "712"),
    Moon("rosalind", "Rosalind", "uranus", 5610, "713"),
    Moon("belinda", "Belinda", "uranus", 5620, "714"),
    Moon("cressida", "Cressida", "uranus", 5630, "709"),

    Moon("triton", "Triton", "neptune", 5700, "801"),
    Moon("nereid", "Nereid", "neptune", 5710, "802"),
    Moon("proteus", "Proteus", "neptune", 5720, "808"),
    Moon("larissa", "Larissa", "neptune", 5730, "807"),
    Moon("galatea", "Galatea", "neptune", 5740, "806"),
    Moon("despina", "Despina", "neptune", 5750, "805"),
    Moon("thalassa", "Thalassa", "neptune", 5760, "804"),
    Moon("naiad", "Naiad", "neptune", 5770, "803"),
    Moon("halimede", "Halimede", "neptune", 5780, "809"),
    Moon("sao", "Sao", "neptune", 5790, "811"),
    Moon("laomedeia", "Laomedeia", "neptune", 5800, "812"),
    Moon("neso", "Neso", "neptune", 5810, "813"),

    Moon("charon", "Charon", "pluto", 5900, "901")
  ];

  private static AuthoritativeCatalogTarget Moon(string slug, string displayName, string parentSlug, int sortOrder, string horizonsCommand)
  {
    return new(slug, displayName, "Moon", "moon", parentSlug, sortOrder, HorizonsCommand: horizonsCommand);
  }

  private static AuthoritativeCatalogTarget Fragment(string slug, string displayName, string parentSlug, int sortOrder, string designation)
  {
    return new(
      slug,
      displayName,
      "Comet Fragment",
      "comet-fragment",
      parentSlug,
      sortOrder,
      SbdbDesignation: designation,
      HorizonsCommand: $"DES={designation};CAP");
  }
}

public sealed record AuthoritativeCatalogTarget(
  string Slug,
  string DisplayName,
  string Category,
  string Kind,
  string? ParentSlug,
  int SortOrder,
  string? SbdbDesignation = null,
  string? HorizonsCommand = null);