namespace Sol.Api.Models;

public sealed record CatalogBodySeed(
  string Slug,
  string DisplayName,
  string Category,
  string Kind,
  string? ParentSlug,
  int SortOrder,
  string MetadataJson,
  string? JplId = null,
  string? MinEpoch = null,
  string? MaxEpoch = null,
  double? Aphelion_AU = null,
  double? Perihelion_AU = null,
  double? Eccentricity = null,
  double? Inclination_deg = null,
  double? SemiMajorAxis_AU = null,
  double? ArgumentOfPerihelion_deg = null,
  double? LongitudeOfAscendingNode_deg = null,
  double? MeanAnomaly_deg = null,
  double? MeanMotion_degPerDay = null,
  double? OrbitalPeriod_days = null,
  double? Epoch_JD = null,
  double? MeanRadius_km = null,
  double? Density_gcm3 = null,
  double? Mass_1e23kg = null,
  double? Volume_1e10km3 = null,
  double? SiderealRotPeriod_d = null,
  double? SiderealRotRate_radps = null,
  double? MeanSolarDay_d = null,
  double? CoreRadius_km = null,
  double? GeometricAlbedo = null,
  double? SurfaceEmissivity = null,
  double? GM_km3s2 = null,
  double? EquatorialRadius_km = null,
  double? MassRatioSunPlanet = null,
  double? MomentOfInertia = null,
  double? EquatorialGravity_ms2 = null,
  double? AtmosPressure_bar = null,
  double? MaxAngularDiam_arcsec = null,
  double? MeanTemperature_K = null,
  double? VisualMag = null,
  double? ObliquityToOrbit_arcmin = null,
  double? HillSphereRadius_Rp = null,
  double? SiderealOrbPeriod_y = null,
  double? SiderealOrbPeriod_d = null,
  double? EscapeVelocity_kms = null,
  double? MeanOrbitVelocity_kms = null,
  double? SolarConstant_Wm2_Mean = null,
  double? SolarConstant_Wm2_Perihelion = null,
  double? SolarConstant_Wm2_Aphelion = null,
  double? MaxPlanetaryIR_Wm2_Mean = null,
  double? MaxPlanetaryIR_Wm2_Perihelion = null,
  double? MaxPlanetaryIR_Wm2_Aphelion = null,
  double? MinPlanetaryIR_Wm2_Mean = null,
  double? MinPlanetaryIR_Wm2_Perihelion = null,
  double? MinPlanetaryIR_Wm2_Aphelion = null,
  // Fields added for redesigned schema
  double? H_AbsMag = null,
  double? G_Slope = null,
  string? Source = null,
  string? SbdbDesignation = null,
  double? EphemerisMinJD = null,
  double? EphemerisMaxJD = null
);
